version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:v1.10.0
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333" # HTTP/REST
      - "6334:6334" # gRPC
    environment:
      QDRANT__LOG_LEVEL: "INFO"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:6333/readyz"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  qdrant_data: {}
